# -*- coding: utf-8 -*-
"""EPICS.pynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ngsgi3HxwvM8OzcMLewTqkMNono3WBLX
"""

from google.colab import files
uploaded = files.upload()

import zipfile
import os

zip_file = list(uploaded.keys())[0]

with zipfile.ZipFile(zip_file, 'r') as zip_ref:
    zip_ref.extractall("data")

print(os.listdir("data"))

import pandas as pd

# replace filename if needed
df = pd.read_csv("data/iot_plant_rl_dataset.csv")

df.head()

print(df.columns)

features = [
    'ACHP', 'PHR', 'AWWGV', 'ALAP', 'ANPL',
    'ARD', 'ADWR', 'PDMVG', 'ARL', 'AWWR',
    'ADWV', 'PDMRG'
]

df = df[features]

df = df.dropna()

threshold = df['AWWGV'].mean()

df['water_needed'] = df['AWWGV'].apply(
    lambda x: 1 if x < threshold else 0
)

X = df.drop(['water_needed', 'AWWGV'], axis=1)  # removed AWWGV
y = df['water_needed']

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier(random_state=42)
dt.fit(X_train, y_train)

from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(n_estimators=100, random_state=42)
rf.fit(X_train, y_train)

from xgboost import XGBClassifier

xgb = XGBClassifier(use_label_encoder=False, eval_metric='logloss')
xgb.fit(X_train, y_train)

from sklearn.metrics import accuracy_score, classification_report
import time

models = {
    "Decision Tree": dt,
    "Random Forest": rf,
    "XGBoost": xgb
}

results = []

for name, model in models.items():

    # ⏱ Training time
    start = time.time()
    model.fit(X_train, y_train)
    train_time = time.time() - start

    # Predictions
    y_pred = model.predict(X_test)

    # Accuracy
    acc = accuracy_score(y_test, y_pred)

    # Error (simple)
    error = 1 - acc

    results.append([name, acc, error, train_time])

# Show results
import pandas as pd
results_df = pd.DataFrame(results, columns=["Model", "Accuracy", "Error", "Training Time"])
print(results_df)

from sklearn.ensemble import RandomForestClassifier

final_model = RandomForestClassifier(n_estimators=100, random_state=42)
final_model.fit(X_train, y_train)

import joblib

joblib.dump(final_model, "irrigation_model.pkl")

def predict_irrigation(input_data):
    prediction = final_model.predict([input_data])
    return "YES" if prediction[0] == 1 else "NO"

import matplotlib.pyplot as plt

importances = final_model.feature_importances_

plt.figure(figsize=(10,5))
plt.bar(X.columns, importances)
plt.xticks(rotation=90)
plt.title("Feature Importance")
plt.show()

# ===============================
# 1. IMPORT LIBRARIES
# ===============================
import requests
import time
import joblib
import pandas as pd

# ===============================
# 2. LOAD MODEL
# ===============================
model = joblib.load("irrigation_model.pkl")

# ===============================
# 3. THINGSPEAK CONFIG
# ===============================
CHANNEL_ID = "3308389"
READ_API_KEY = "ING3I9KINHYOTLHB"
WRITE_API_KEY = "6XJ3FC1MV437RCIV"

# ===============================
# 4. SAFE FLOAT
# ===============================
def safe(val):
    try:
        return float(val) if val not in [None, ""] else 0.0
    except:
        return 0.0

# ===============================
# 5. SEND OUTPUT
# ===============================
def send_to_thingspeak(pump):
    url = "https://api.thingspeak.com/update"
    params = {
        "api_key": WRITE_API_KEY,
        "field6": pump
    }
    requests.get(url, params=params)

# ===============================
# 6. RUN SYSTEM
# ===============================
def run_system():
    try:
        # ===== FETCH DATA =====
        url = f"https://api.thingspeak.com/channels/{CHANNEL_ID}/feeds/last.json?api_key={READ_API_KEY}"
        data = requests.get(url).json()

        print("Raw Data:", data)

        # ===== SENSOR VALUES =====
        temp = safe(data.get("field1"))
        humidity = safe(data.get("field2"))
        soil = safe(data.get("field3"))
        light = safe(data.get("field4"))
        rain = safe(data.get("field5"))

        # ===============================
        # 7. CREATE FEATURE VECTOR (11 FEATURES)
        # ===============================
        input_data = [
            temp,      # ACHP
            humidity,  # PHR
            light,     # ALAP
            rain,      # ANPL
            10,        # ARD (dummy)
            5,         # ADWR
            7,         # PDMVG
            2,         # ARL
            8,         # AWWR
            4,         # ADWV
            6          # PDMRG
        ]

        # Convert to DataFrame (fix warning)
        columns = [
            'ACHP', 'PHR', 'ALAP', 'ANPL',
            'ARD', 'ADWR', 'PDMVG', 'ARL',
            'AWWR', 'ADWV', 'PDMRG'
        ]

        input_df = pd.DataFrame([input_data], columns=columns)

        # ===============================
        # 8. PREDICTION
        # ===============================
        prediction = model.predict(input_df)[0]

        pump = 1 if prediction == 1 else 0

        # ===============================
        # 9. SEND OUTPUT
        # ===============================
        send_to_thingspeak(pump)

        # ===============================
        # 10. DISPLAY
        # ===============================
        print("\n--- LIVE PREDICTION ---")
        print(f"Temperature: {temp}")
        print(f"Humidity: {humidity}")
        print(f"Soil: {soil}")
        print(f"Light: {light}")
        print(f"Rain: {rain}")

        if pump == 1:
            print("🚿 Irrigation Needed: YES")
        else:
            print("❌ Irrigation Needed: NO")

    except Exception as e:
        print("Error:", e)

# ===============================
# 11. LOOP
# ===============================
while True:
    run_system()
    time.sleep(15)

from sklearn.ensemble import RandomForestClassifier
import joblib

final_model = RandomForestClassifier(n_estimators=100, random_state=42)
final_model.fit(X_train, y_train)

joblib.dump(final_model, "irrigation_model.pkl")

from google.colab import files
files.download("irrigation_model.pkl")